### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by andrelmariano** [doggo1000/Twitch-Follow-Bot#1]
It does not work

Channel: andzerafps
Amount: 2
Sending 2 twitch followers to andzerafps!
Loaded 1 tokens!
[{"errors":[{"message":"unauthenticated","path":["followUser"]}],"data":{"followUser":null},"extensions":{"durationMilliseconds":1,"operationName":"FollowButton_FollowUser","requestID":"01F475ZWFQSBPGPFPG592V7PHE"}}]
[{"errors":[{"message":"unauthenticated","path":["followUser"]}],"data":{"followUser":null},"extensions":{"durationMilliseconds":2,"operationName":"FollowButton_FollowUser","requestID":"01F475ZWFRB89HSS3BZXAM11DT"}}]

**Comment by doggo1000** [comment]
It means your tokens are invalid

**Comment by andrelmariano** [comment]
explain to me how to get the tokens?

**Comment by doggo1000** [comment]
It's the auth-token cookie on twitch. I guess you could generate them.

**Comment by andrelmariano** [comment]
it helps me ? I don't know exactly where to get this, and on my account?

**Comment by doggo1000** [comment]
ill put some free tokens in a sec

**Comment by doggo1000** [comment]
enjoy 
https://github.com/doggo1000/Twitch-Follow-Bot/blob/main/free-tokens.txt

**Comment by andrelmariano** [comment]
thank you, also explains where to add please

**Comment by andrelmariano** [comment]
and where do i use it?

**Comment by doggo1000** [comment]
put them in tokens.txt

**Comment by doggo1000** [comment]
does it work now?

**Comment by andrelmariano** [comment]
VERY GOOD, they work very well, can you tell me where I can get these free tokens?

**Comment by andrelmariano** [comment]
do you have any live views bot?

**Comment by doggo1000** [comment]
Not yet

You need your own way to get the tokens.

**Comment by andrelmariano** [comment]
OK, thanks for the help. when you have the views bot tell me

**Comment by andrelmariano** [comment]
I have a list with 62 thousand tokens, but it doesn't work, you know why?

error
{"error":"Unauthorized","status":401,"message":"The \"Authorization\" token is invalid."}
{"error":"Unauthorized","status":401,"message":"The \"Authorization\" token is invalid."}

**Comment by andrelmariano** [comment]
![image](https://user-images.githubusercontent.com/4019432/116127775-992f7580-a69e-11eb-92cc-87b9bc7a6a9b.png)

**Comment by doggo1000** [comment]
They just don't
